[package]
name = "llhd-sim"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

[dependencies]
llhd = { git = "https://github.com/fabianschuiki/llhd", rev = "a21d432" }
clap = "2.24.2"
num = "0.1"
rayon = "0.7.1"
